<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>teavm-bootstrap-widget-tests</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>..</relativePath>
  </parent>

  <artifactId>teavm-bootstrap3-tests</artifactId>
  <name>TeaVM Bootstrap 3 Widget Tests</name>

  <dependencies>
    <dependency>
      <groupId>io.instanto</groupId>
      <artifactId>teavm-bootstrap3</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.instanto</groupId>
      <artifactId>bootstrap-widget-specifications</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.instanto</groupId>
      <artifactId>cucumber-tea</artifactId>
      <version>${cucumber-tea.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.instanto</groupId>
      <artifactId>cucumber-tea-codegen</artifactId>
      <version>${cucumber-tea.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.instanto</groupId>
      <artifactId>webapp-testkit-dom</artifactId>
      <version>${webapp-testkit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-junit</artifactId>
      <version>${teavm.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
      <version>${teavm.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven-surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <teavm.junit.target>${project.build.directory}/teavm-tests</teavm.junit.target>
            <teavm.junit.js.runner>${teavm.junit.js.runner}</teavm.junit.js.runner>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
