<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>gwt-bootstrap-widgets</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>..</relativePath>
  </parent>

  <artifactId>gwt-bootstrap5-browser-fixtures</artifactId>
  <name>GWT Bootstrap 5 Browser Fixtures</name>
  <packaging>war</packaging>

  <properties>
    <webappDirectory>${project.build.directory}/${project.build.finalName}</webappDirectory>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.gwtproject</groupId>
      <artifactId>gwt-user</artifactId>
      <version>${gwt.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.gwtproject</groupId>
      <artifactId>gwt-dev</artifactId>
      <version>${gwt.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>gwt-bootstrap5</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>gwt-bootstrap5-themes</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <outputDirectory>${webappDirectory}/WEB-INF/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>net.ltgt.gwt.maven</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>${gwt-maven-plugin.version}</version>
        <extensions>true</extensions>
        <configuration>
          <moduleName>io.instanto.bootstrap.testing.gwt5.Bootstrap5BrowserFixtures</moduleName>
          <launcherDir>${webappDirectory}</launcherDir>
          <deploy>${webappDirectory}</deploy>
          <extra>${webappDirectory}</extra>
          <compilerArgs>
            <compilerArg>-saveSource</compilerArg>
          </compilerArgs>
          <jvmArgs>
            <jvmArg>--add-opens=java.base/java.lang=ALL-UNNAMED</jvmArg>
          </jvmArgs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.4.0</version>
      </plugin>
    </plugins>
  </build>
</project>
