<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>gwt-bootstrap-widgets</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>gwt-bootstrap3-showcase</artifactId>
  <name>GWT Bootstrap 3 Showcase</name>
  <packaging>war</packaging>

  <properties>
    <webappDirectory>${project.build.directory}/${project.build.finalName}</webappDirectory>
    <validation.version>1.0.0.GA</validation.version>
    <hibernate-validator.version>4.1.0.Final</hibernate-validator.version>
    <slf4j.version>1.7.12</slf4j.version>
    <universal-analytics.version>2.1</universal-analytics.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.gwtproject</groupId>
      <artifactId>gwt-user</artifactId>
      <version>${gwt.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.gwtproject</groupId>
      <artifactId>gwt-dev</artifactId>
      <version>${gwt.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>gwt-bootstrap3</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>gwt-bootstrap3-extras</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>gwt-bootstrap3-themes</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
      <version>${validation.version}</version>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
      <version>${validation.version}</version>
      <classifier>sources</classifier>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-validator</artifactId>
      <version>${hibernate-validator.version}</version>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-validator</artifactId>
      <version>${hibernate-validator.version}</version>
      <classifier>sources</classifier>
    </dependency>
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>2.3.9</version>
    </dependency>
    <dependency>
      <groupId>com.arcbees.analytics</groupId>
      <artifactId>universal-analytics</artifactId>
      <version>${universal-analytics.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.gwt</groupId>
          <artifactId>gwt-user</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
  </dependencies>

  <build>
    <outputDirectory>${webappDirectory}/WEB-INF/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>net.ltgt.gwt.maven</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>${gwt-maven-plugin.version}</version>
        <extensions>true</extensions>
        <configuration>
          <moduleName>org.gwtbootstrap3.demo.GwtBootstrap3Demo</moduleName>
          <launcherDir>${webappDirectory}</launcherDir>
          <deploy>${webappDirectory}</deploy>
          <extra>${webappDirectory}</extra>
          <compilerArgs>
            <compilerArg>-saveSource</compilerArg>
          </compilerArgs>
          <jvmArgs>
            <jvmArg>--add-opens=java.base/java.lang=ALL-UNNAMED</jvmArg>
          </jvmArgs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.4.0</version>
      </plugin>
    </plugins>
  </build>
</project>
